services:
  okarea:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: okarea
    restart: unless-stopped
    ports:
      - "3001"
    networks:
      - proxy

networks:
  proxy:
    external: true
